export { passwordChangedEmailTemplate } from './change-password.template'
export { accountDeactivatedEmailTemplate } from './deactivate-account.template'
export { mobileResetPasswordEmailTemplate } from './forgot-email-mobile.template'
export { resetPasswordEmailTemplate } from './forgot-email.template'
export { codeOnlyEmailTemplate } from './welcome-mobile.template'
export { welcomeEmailTemplate } from './welcome.template'