export { CategoryRoutes } from './category.routes'
export { UserRoutes } from './user.routes'
export { SupplierRoutes } from './supplier.routes'
export { ProductRoutes } from './product.routes'
export { ReportRoutes } from './report.routes'
export { SaleRoutes } from './sale.routes'